# Generated by Django 4.2.23 on 2025-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_expense_category_financialalert_monthlyincome"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlyincome",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="monthlyincome",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="monthlyincome",
            name="income_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="monthlyincome",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
    ]
