# Generated by Django 4.2.23 on 2025-08-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_monthlyincome_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlyincome",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="monthlyincome",
            old_name="month",
            new_name="date",
        ),
    ]
