version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_APP_NAME=Despesa Certa
    restart: unless-stopped
