version: '3.9'

services:
  backend:
    build: ./backend_expenses
    command: gunicorn backend_expenses.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60
    ports:
      - "8000:8000"
    env_file:
      - .env.aws
    environment:
      - RUNNING_IN_DOCKER=1
      - DJANGO_SETTINGS_MODULE=backend_expenses.settings.production
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://15.228.243.19:8000/api
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=despesa_certa
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
