version: '3.9'

services:
  backend:
    build: .
    command: gunicorn backend_expenses.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: despesa_certa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
